// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';
import {appconfig} from '../models';

export function GetAvailableAddrs():Promise<Array<gui.NetInterfaceAddress>>;

export function GetConfig():Promise<appconfig.AppConfig>;

export function GetServerStatus():Promise<gui.ServerStatus>;

export function PickFilePath():Promise<string>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;

export function UpdateAuthEnabled(arg1:boolean):Promise<void>;

export function UpdateAuthPassword(arg1:string):Promise<void>;

export function UpdateAuthUsername(arg1:string):Promise<void>;

export function UpdateResponseHeaders(arg1:Record<string, string>):Promise<void>;

export function UpdateServerHost(arg1:string):Promise<void>;

export function UpdateServerPort(arg1:number):Promise<void>;

export function UpdateTLSCertFile(arg1:string):Promise<void>;

export function UpdateTLSEnabled(arg1:boolean):Promise<void>;

export function UpdateTLSKeyFile(arg1:string):Promise<void>;
