// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableAddrs() {
  return window['go']['gui']['App']['GetAvailableAddrs']();
}

export function GetConfig() {
  return window['go']['gui']['App']['GetConfig']();
}

export function GetServerStatus() {
  return window['go']['gui']['App']['GetServerStatus']();
}

export function PickFilePath() {
  return window['go']['gui']['App']['PickFilePath']();
}

export function StartServer() {
  return window['go']['gui']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['gui']['App']['StopServer']();
}

export function UpdateResponseHeaders(arg1) {
  return window['go']['gui']['App']['UpdateResponseHeaders'](arg1);
}

export function UpdateServerHost(arg1) {
  return window['go']['gui']['App']['UpdateServerHost'](arg1);
}

export function UpdateServerPort(arg1) {
  return window['go']['gui']['App']['UpdateServerPort'](arg1);
}

export function UpdateTLSCertFile(arg1) {
  return window['go']['gui']['App']['UpdateTLSCertFile'](arg1);
}

export function UpdateTLSEnabled(arg1) {
  return window['go']['gui']['App']['UpdateTLSEnabled'](arg1);
}

export function UpdateTLSKeyFile(arg1) {
  return window['go']['gui']['App']['UpdateTLSKeyFile'](arg1);
}
