// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableAddrs() {
  return window['go']['main']['App']['GetAvailableAddrs']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function UpdateServerHost(arg1) {
  return window['go']['main']['App']['UpdateServerHost'](arg1);
}

export function UpdateServerPort(arg1) {
  return window['go']['main']['App']['UpdateServerPort'](arg1);
}
