// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAvailableAddrs():Promise<Array<main.NetInterfaceAddress>>;

export function GetConfig():Promise<main.AppConfig>;

export function GetServerStatus():Promise<main.ServerStatus>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;

export function UpdateServerHost(arg1:string):Promise<void>;

export function UpdateServerPort(arg1:number):Promise<void>;
